"""Distance-binned bias loader + apply layer.

File format (JSON, generated by `scripts/validate_stage1_itu.py
--dump-bias-dir`):

    {
      "gateway_code": "7276ff002e0507da",
      "n_samples": 197,
      "model_version": "stage1-itu-p1812-...",
      "generated_at": "2026-05-28T...",
      "bins": [
        {"d_min_km": 0.0, "d_max_km": 1.0, "mean_residual_db": -12.2, "n": 133},
        {"d_min_km": 1.0, "d_max_km": 2.0, "mean_residual_db":  -8.2, "n":  63},
        ...
      ]
    }

`mean_residual_db = measured_rssi - predicted_rssi`. Vì measured ≤ predicted
khi model under-estimates path loss, residual âm = model thiếu PL → bias
nên cộng **+|residual|** vào PL_predicted để khớp measured RSSI.

Apply rule (signed):

    PL_corrected = PL_raw - mean_residual_db
                = PL_raw + (predicted_rssi - measured_rssi)

(Khử bias trung bình; spread σ_L vẫn do P.1812 location variability lo.)
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from pathlib import Path
from threading import Lock
from typing import Final

log = logging.getLogger(__name__)

# Cap bias để tránh outlier survey "ăn" cả band — vd Hải Phòng row gắn nhầm
# gw Đà Nẵng (~554 km) có thể tạo residual >30 dB. Validate script filter
# d<50km nhưng bias loader cap thêm tầng 2 cho an toàn.
MAX_ABS_BIAS_DB: Final[float] = 25.0


@dataclass(frozen=True, slots=True)
class _Bin:
    d_min_km: float
    d_max_km: float
    mean_residual_db: float
    n: int


@dataclass
class DistanceBinnedBias:
    """Lazy-load bias per gateway từ thư mục `bias_dir/bias_<code>.json`.

    Cache per-gateway sau lần load đầu. File missing → trả 0 dB (no-op).
    Thread-safe qua Lock đơn (load 1 lần, sau đó readonly).

    Usage:
        bias = DistanceBinnedBias(Path("apps/web-app/public/coverage/minsf"))
        offset_db = bias.bias_db("7276ff002e0507da", distance_km=1.5)
        pl_corrected = pl_raw - offset_db  # offset is `mean_residual` (signed)
    """

    bias_dir: Path
    _cache: dict[str, tuple[_Bin, ...] | None] = field(default_factory=dict, repr=False)
    _lock: Lock = field(default_factory=Lock, repr=False)

    def _load(self, gw_code: str) -> tuple[_Bin, ...] | None:
        with self._lock:
            if gw_code in self._cache:
                return self._cache[gw_code]
            path = self.bias_dir / f"bias_{gw_code}.json"
            if not path.is_file():
                self._cache[gw_code] = None
                return None
            try:
                raw = json.loads(path.read_text(encoding="utf-8"))
                bins = tuple(
                    _Bin(
                        d_min_km=float(b["d_min_km"]),
                        d_max_km=float(b["d_max_km"]),
                        mean_residual_db=float(b["mean_residual_db"]),
                        n=int(b.get("n", 0)),
                    )
                    for b in raw.get("bins", [])
                )
            except (json.JSONDecodeError, KeyError, ValueError, TypeError) as e:
                log.warning(
                    "Bias file %s parse failed (%s) — treating as no-bias.", path, e
                )
                bins = ()
            self._cache[gw_code] = bins if bins else None
            return self._cache[gw_code]

    def residual_db(self, gw_code: str, distance_km: float) -> float:
        """Lookup residual cho distance bin.

        - Trong bin: trả mean_residual_db của bin đó.
        - Ngoài range tất cả bin: clamp về bin gần nhất (extrapolate flat).
        - File missing / empty: return 0.0.

        Cap |residual| ≤ MAX_ABS_BIAS_DB để outlier không bóp méo map.
        """
        bins = self._load(gw_code)
        if not bins:
            return 0.0
        # Tìm bin chứa distance_km
        for b in bins:
            if b.d_min_km <= distance_km < b.d_max_km:
                return _clamp(b.mean_residual_db, MAX_ABS_BIAS_DB)
        # Ngoài range → clamp về bin gần nhất theo center
        first, last = bins[0], bins[-1]
        if distance_km < first.d_min_km:
            return _clamp(first.mean_residual_db, MAX_ABS_BIAS_DB)
        return _clamp(last.mean_residual_db, MAX_ABS_BIAS_DB)

    def bias_db(self, gw_code: str, distance_km: float) -> float:
        """Trả offset cộng-vào-PL_raw (= -residual_db).

        Convention:
            residual = measured - predicted  (âm = predict cao hơn thật)
            PL_corrected = PL_raw - residual  → khử bias trung bình
        """
        return -self.residual_db(gw_code, distance_km)


def _clamp(x: float, abs_cap: float) -> float:
    if x > abs_cap:
        return abs_cap
    if x < -abs_cap:
        return -abs_cap
    return x
