/**
 * strings.js — Centralizes all UI display text.
 */

const S = {

  nav: {
    map:         "Map",
    simulator:   "Simulator",
    health:      "Health Dashboard",
    calibration: "Calibration",
    compare:     "Compare Scenarios",
    sandbox:     "Sandbox API",
    snapshots:   "Snapshots",
    webhooks:    "Webhooks",
    mobile:      "Mobile (P5)",
  },

  toolbar: {
    sectionCampaign: "Campaign",
    sectionDisplayMode: "Display Mode",
    modes: {
      scatter:   "Measurement Points",
      heat:      "Density and Signal Strength",
      "ml-heat": "ML Heatmap",
    },
    sectionMapStyle:   "Map Style",
    sectionLighting:   "Lighting",
    sectionLayers:     "Map Layers",
    showGateways:      "📡 Show Gateways",
    hideGateways:      "📡 Hide Gateways",
    showRangeCircles:  "🔵 Show Theoretical Coverage",
    hideRangeCircles:  "🔵 Hide Theoretical Coverage",
    radius: "Radius",
    radiusMin: "0.5 km",
    radiusMax: "10 km",
    radiusMid: "5 km",
    sectionRssiFilter: "Minimum RSSI Threshold",
    rssiUnit:          "dBm",
    rssiAxisMin:       "-120",
    rssiAxisMid:       "-80",
    rssiAxisMax:       "-40 dBm",
    sectionSF:         "Spreading Factor",
    sfAll:             "All",
    mlRunning:         "Computing...",
    mlRerun:           "Rerun ML",
    mlRun:             "Run ML IDW",

    sectionExport:     "Export Data",
    exportGeoJson:     "⬇️ GeoJSON",
    exportKml:         "⬇️ KML (Google Earth)",
    exportBoq:         "⬇️ BoQ Excel",
    exportPdf:         "⬇️ PDF Report",
  },

  stats: {
    title: "Statistics",
    totalPoints: "Total Measurements",
    avgRssi:     "Average RSSI",
    maxRssi:     "Strongest RSSI",
    minRssi:     "Weakest RSSI",
    avgSnr:      "Average SNR",
    displaying:  "Displaying",
    pointsUnit:  "points",
    sectionCoverage: "Coverage Distribution",
    coverageStrong:   "Strong (≥ −90 dBm)",
    coverageMedium:   "Medium (−90 ~ −105 dBm)",
    coverageWeak:     "Weak (−105 ~ −120 dBm)",
    coverageVeryWeak: "Very Weak (< −120 dBm)",
    sectionML:        "ML Prediction",
    gridPoints:       "Grid Points",
    avgPredRssi:      "Avg Predicted RSSI",
    avgUncertainty:   "Avg Uncertainty",
    sectionMetrics:   "Evaluation Metrics",
    metricRmse:       "RMSE",
    metricMae:        "MAE",
    metricR2:         "R²",
    mlGood:     " Model fits real data well.",
    mlMedium:   " Model fits moderately, more measurements needed.",
    mlBad:      " Model is poor, areas lack measurement points.",
    mlNoMetric: "No evaluation metrics yet. Click \"Rerun ML\" to compute.",
    sectionUncertainty: "Uncertainty",
    uncertaintyLevels: [
      { label: "Confident (< 3 dB)" },
      { label: "Medium (3–6 dB)" },
      { label: "Poor (6–10 dB)" },
      { label: "Very Poor (> 10 dB)" },
    ],
    sectionSignal: "Signal Strength",
    signalLevels: [
      { label: "Strong (≥ −90 dBm)" },
      { label: "Medium (−90 ~ −105)" },
      { label: "Weak (−105 ~ −120)" },
      { label: "Very Weak (< −120)" },
    ],
  },

  scatter: {
    popupRssi: "RSSI:",  popupSnr: "SNR:",  popupSf: "SF:",  popupGw: "GW:",
    popupUnknown: "—",   SNR_link: "📶 SNR LINK QUALITY",
  },

  gateway: {
    defaultName: "Gateway",
    altitude: "Altitude:", altitudeUnit: "m",
    antenna:  "Antenna:", antennaUnit:  "m",
  },

  app: {
    defaultCampaignName: "Drive Test Q1-2025",
    toastRunning:    "Running IDW interpolation...",
    toastDone:       (points, sec) => `Done! ${points} grid points (${sec}s)`,
    toastError:      (msg) => "Error: " + msg,
    toastSimulating: "Simulating coverage...",
    toastOptimizing: "Finding optimal location...",
  },

  mobile: {
    title:    "Got Signal?",
    subtitle: "Tap the button to check coverage at your location",
    idle:     "Not checked yet",
    scanning: "Locating…",
    scanButton:     "📍 Scan My Location",
    scanButtonAria: "Scan current GPS coordinates and check coverage",
    retry:          "Scan again",
    basedOn: (n) =>
      n === 0 ? "No recent measurement data here"
              : `Based on ${n} recent measurements`,
    nearestGateway:  "Nearest Gateway",
    unnamedGw:       "Gateway",
    directionPrefix: "Direction",
    meterUnit:       "m",
    suggestionTitle:    "Suggestion",
    suggestionNotFound: "No better signal data around your area.",
    expectedAfter:      "Expected there:",
    pathTitle:          "Path to better coverage",
    pathStep:           (n, dir, m) => `Step ${n}: go ${m}m towards ${dir}`,
    pathSummary:        (steps, m) => `Total: ${steps} steps · ${m}m`,
    pathExpectedFinal:  "Expected at endpoint:",
    pathNoSteps:        "No need to move — you are already at the best spot nearby.",
    errorGeneric:        "An error occurred, please try again.",
    errorGpsUnsupported: "Browser does not support GPS positioning.",
    errorGpsDenied:      "You denied GPS access. Please re-enable it in settings.",
    errorGpsFailed:      "Could not get GPS location. Try a more open area.",
  },

  simulator: {
    title:           "Coverage Simulation",
    hint:            "Click the map to add a hypothetical gateway",
    transmittersN:   (n) => `${n} gateway`,
    btnRun:          "▶ Run Simulation",
    btnRunning:      "Running...",
    btnClear:        "🗑 Clear All",
    sectionEnv:      "Environment",
    envOptions: {
      urban:    "Urban",
      suburban: "Suburban",
      rural:    "Rural",
      forest:   "Forest",
      coastal:  "Coastal",
      mountain: "Mountain",
    },
    sectionResolution: "Grid Resolution (m)",
    sectionTxPower:    "TX Power (dBm)",
    sectionAntenna:    "Antenna gain (dBi)",
    sectionAntennaHeight: "Antenna Height (m)",
    sectionUseCalibration: "Use Calibration from DB",
    useCalibrationHint:    "Override model with field-calibrated parameters",
    noTransmitters:    "No gateway yet. Please click the map.",
    staleWarning : "⚠ Parameters changed — rerun to update results",
  },

  health: {
    title:    "Gateway Status",
    subtitle: "Real-time uptime monitoring of base stations",
    summaryOnline: "Online", summaryDegraded: "Degraded",
    summaryOffline:"Offline", summaryTotal:    "Total",
    colName:  "Gateway", colEui: "EUI", colStatus: "Status",
    colLastSeen: "Last Seen", colUplinks: "Uplinks 24h", colUptime: "Uptime 24h",
    statusOnline: "Online", statusDegraded: "Degraded", statusOffline: "Offline",
    neverSeen:    "No uplink yet",
    hoursAgo:     (h) => h < 1   ? "just now"
                        : h < 24 ? `${Math.round(h)} hours ago`
                                 : `${Math.round(h / 24)} days ago`,
    empty: "No gateways yet.",
    reload: "🔄 Reload",
  },

  calibration: {
    title:    "Calibration with Real Measurement Data",
    subtitle: "Upload ground-truth CSV to calibrate the prediction model",
    campaign: "Campaign",
    uploadHint:     "CSV must include columns: lat, lng, rssi_dbm (required)",
    uploadOptional: "Optional columns: snr_db, spreading_factor, gateway_eui, measured_at",
    btnPick:     "📁 Choose CSV File",
    btnUpload:   "⬆️ Upload & Calibrate",
    btnUploading:"Processing...",
    noFile:      "No file selected",
    resultTitle: "Result",
    rowsInFile:  "Total rows in file",
    inserted:    "Inserted into DB",
    skipped:     "Skipped",
    metricsTitle:"Error vs Prediction",
    metricsRmse: "RMSE (dB)",
    metricsMae:  "MAE (dB)",
    metricsBias: "Bias (dB)",
    metricsN:    "Number of compared pairs",
    noMetrics:   "No ml_predictions yet. Run /predict/run first to have comparison data.",
    biasHint:    "Bias > 0: model predicts higher than actual.",
  },

  compare: {
    title:    "Compare A/B Scenarios",
    subtitle: "Evaluate coverage differences between 2 predicted scenarios",
    campaignA: "Scenario A", campaignB: "Scenario B",
    btnRun:    "▶ Compare",  btnRunning: "Computing...",
    sameError: "Please select 2 different scenarios.",
    summaryTitle: "Difference Summary (B − A)",
    matchedCells: "Matched cells",
    onlyInA:      "Only in A",
    onlyInB:      "Only in B",
    avgDelta:     "Avg Δ RSSI (dB)",
    maxGain:      "Max improvement (dB)",
    maxLoss:      "Max degradation (dB)",
    strongChange: "% change in Strong area",
    mediumChange: "% change in Medium area",
    distTitle: "Coverage Distribution",
    colLevel: "Level", colA: "A", colB: "B", colDiff: "Δ",
  },

  // ─────────────────────────────────────────────
  // Persona 6 — Sandbox API
  // ─────────────────────────────────────────────
  sandbox: {
    title:    "Sandbox API",
    subtitle: "Test custom parameters to predict RSSI at a single point",

    sectionTx:          "Transmitter (TX)",
    sectionRx:          "Receiver (RX)",
    sectionPhysical:    "Physical Parameters",
    labelLat:           "Latitude",
    labelLng:           "Longitude",
    labelTxPower:       "TX Power (dBm)",
    labelAntennaGain:   "Antenna gain (dBi)",
    labelEnv:           "Environment",
    labelSf:            "Spreading Factor",
    labelExpOverride:   "Path Loss Exponent (override, leave blank = auto by environment)",
    btnRunPoint:        "▶ Compute RSSI at RX",
    btnRunRadial:       "📈 Plot curve by radius",
    btnRunning:         "Computing...",

    resultTitle:        "Result",
    labelDistance:      "Distance",
    labelPathLoss:      "Path Loss",
    labelExp:           "Path Loss Exponent in use",
    labelPredicted:     "Predicted RSSI",
    labelSensitivity:   "Sensitivity (SF)",
    labelLinkMargin:    "Link Margin",
    labelDecodeable:    "Decodable",
    labelDecodeYes:     "Yes",
    labelDecodeNo:      "No",
    labelLevel:         "Classification",

    curveTitle:         "Path Loss vs Distance Chart",
    curveXLabel:        "Distance (m)",
    curveYLabel:        "RSSI (dBm)",
    noCurve:            "Click \"Plot curve\" to display the chart.",
  },

  // ─────────────────────────────────────────────
  // P2 / P4 — Outbound Webhooks
  // ─────────────────────────────────────────────
  webhooks: {
    title:    "Outbound Webhooks",
    subtitle: "Get notified when a gateway goes offline or other events occur",

    sectionList:   "Subscription List",
    sectionCreate: "Create New Subscription",

    labelProjectId:  "Project ID",
    labelName:       "Name (description)",
    labelTargetUrl:  "Target URL (https://…)",
    labelEvents:     "Event types (comma-separated, leave blank = all)",
    btnCreate:       "✚ Create",
    btnTest:         "Test",
    btnDelete:       "Delete",
    btnDeliveries:   "History",
    btnReload:       "🔄 Reload",

    colName:    "Name",
    colUrl:     "URL",
    colEvents:  "Events",
    colActive:  "Active",
    colActions: "Actions",

    eventsAll:  "All",

    newSecret:  "🔑 Secret (save it — cannot be viewed again):",
    copyHint:   "Click to copy",
    copied:     "Copied!",

    empty:      "No subscriptions yet.",
    testFired:  (delivered, failed) =>
                `Sent: ${delivered} successful, ${failed} failed`,

    deliveriesTitle: "Delivery History (latest 50)",
    colEvent:    "Event",
    colStatus:   "Status",
    colDuration: "Duration",
    colError:    "Error",
    colTime:     "Time",
  },

  snapshots: {
    title:    "Prediction History",
    subtitle: "Manage prediction grid versions of the campaign",
    campaign: "Campaign",
    reload:   "🔄 Reload",
    empty:    "No snapshots yet.",
    colCreatedAt: "Timestamp",
    colAlgorithm: "Algorithm",
    colLabel:     "Label",
    colCount:     "Grid Cells",
    colAvg:       "Avg RSSI",
    colActions:   "Actions",
    btnRestore:   "↻ Restore",
    btnDelete:    "🗑 Delete",
    confirmRestore: "Restore this snapshot? The current grid will be snapshotted first.",
    confirmDelete:  "Permanently delete this snapshot?",
    restored: (n) => `Restored ${n.toLocaleString()} grid points.`,
  },
  optimizer: {
    title:        "Gateway Location Optimization",
    hint:         "Suggest optimal gateway locations for Da Nang (Greedy MCLP/LSCP)",

    tabSimulate:  "Hypothetical Click",
    tabOptimize:  "Optimize Location",

    sectionLayers:    "Display Layers",
    showAoi:          "AOI Region (entire Da Nang)",
    showUrban:        "Urban Area",
    showCandidates:   "Candidates (grid + infra)",

    sectionConfig:        "Optimization Settings",
    modeMclp:             "MCLP — fixed K",
    modeLscp:             "LSCP — reach %",
    labelKMax:            "Number of gateways K",
    labelTargetCoverage:  "% target coverage",
    labelSf:              "Spreading Factor",
    labelTxPower:         "TX Power",
    labelTxHeight:        "Antenna Height",
    labelCostAware:       "Cost-aware (prefer cheap infra)",

    btnRun:               "▶ Run Optimization",
    btnRunning:           "Computing...",

    sectionResult:        "Result",
    resultK:              "Number of gateways",
    resultCoverage:       "Coverage Ratio",
    resultCost:           "Total Cost",
    resultCompute:        "Compute Time",
    resultIterations:     "Iterations",
    resultTopSelections:  "Top selections (ranked by gain)",

    sectionHistory:       "Run History",
    emptyHistory:         "No runs yet. Click \"Run Optimization\".",
    btnDelete:            "Delete run",

    toastSuccess: (n, ratio) =>
      `✓ Selected ${n} gateways, covering ${(ratio * 100).toFixed(1)}%`,
  },
};

export default S;
